---

pull_request_rules:
  - name: automatic merge with strict
    conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - label!=do-not-merge
      - status-success=Travis CI - Pull Request
      - status-success=DCO
    actions:
      merge:
        method: merge
        strict: true
