---

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: snapshotpolicies.snapscheduler.backube
spec:
  group: snapscheduler.backube
  names:
    kind: SnapshotPolicy
    listKind: SnapshotPolicyList
    plural: snapshotpolicies
    singular: snapshotpolicy
  scope: Cluster
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            retention:
              properties:
                maxCount:
                  format: int32
                  minimum: 1
                  type: integer
              type: object
            schedule:
              pattern: ^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$
              type: string
          type: object
        status:
          properties:
            cronJob:
              properties:
                name:
                  type: string
                namespace:
                  type: string
              type: object
          type: object
  version: v1alpha1
  versions:
    - name: v1alpha1
      served: true
      storage: true
